version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.8
  build:
    commands:
      - pip install --upgrade awscli
      - pip install -r requirements.txt
      - python -m unittest discover -s ./src/test
